### ISSUE TITLE
what is the proper way to reset a tournament?

### ISSUE THREAD

**Issue by seiyria** [clux/tournament#24]
I'm thinking I can just wipe `state`, but I'm not sure if the internals will clean that up properly.

**Comment by clux** [comment]
You are just meant to create a new one with the same constructor parameters. If you want to restore a saved one you can use [restore](https://github.com/clux/tournament/blob/master/doc/base.md#serialization) using the `state`

**Comment by seiyria** [comment]
Sure, that also makes sense. Thanks!
