### ISSUE TITLE
further explanation of trn.unscorable

### ISSUE THREAD

**Issue by seiyria** [clux/tournament#30]
I'm unsure of what these arguments mean, and an example would be really helpful. The function in question is [this one](https://github.com/clux/tournament/blob/master/doc/base.md#trnunscorablematchid-mapscore-allowpast--string--null).

**Comment by clux** [comment]
Hey. Most of that stuff should be explained [further down](https://github.com/clux/tournament/blob/master/doc/base.md#ensuring-scorability--consistency).

After reading that, it's mostly useful for control of rewriting history. Like in duel tournaments where you may or may not want people changing the outcomes of the quarter finals if the semi finals have already been played. `allowPast` explicitly allows this.

**Comment by seiyria** [comment]
Interesting. That's fair. I definitely am used to documentation being of a different structure, sorry (and also, some days my eyes don't work, haha)!

**Comment by clux** [comment]
No worries :)
