### ISSUE TITLE
What to do about no-shows?

### ISSUE THREAD

**Issue by seiyria** [clux/tournament#31]
This is a question that has been brought up to me a few times, and the answer from me was "I dunno, give them a loss?"

I figured it was worth asking, since not all tournaments are made perfect - what do you do if you have a no-show? Score a loss for them (ie, 1/0)? Remove them (although this has other implications, esp. if later in the tournament)?

Is it even worth scoping such a thing into the tournament base?

**Comment by clux** [comment]
Scoring the match a loss for the no-show is the correct thing to do as far as propagation is concerned, and that's what tournament is good at. Removing a player has negative implications.

For user interface stuff; displaying a no-show, an abandoned player, or allowing a different scoring method, that's probably something for you to decide. I don't really want metadata like this to creep into tournament, and you can probably keep some map of match ids to metadata if you want a richer UI. That's my initial opinion of this at least.

**Comment by seiyria** [comment]
That's totally fine. I wanted to double check before doing anything because if this was planned or scoped I didn't want to do something incompatible. Thanks for the comment!
