### ISSUE TITLE
Cant render tournaments correctly

### ISSUE THREAD

**Issue by rigoparis** [clux/tournament#33]
Hey!

I was wondering if you had or used any specific module to render the tournaments, I've been trying the implementation myself, but I can't fully render a bracket form tournament... having issues with spacing and line drawing between rounds...

Wondering if you used a prefered module for rendering or maybe if you had tips for rendering the tournaments

Thanks!

**Comment by clux** [comment]
Hey, yeah that is a difficult bit. I don't have anything myself for it at the moment. You'd just have to figure out all the different `2^{n-k}` style maths yourself really - it's doable, but difficult.

The only implementation I know off the top of my head is  [tournamentmango](http://tournamentmango.com/). Their [source](https://github.com/seiyria/tournamentmango) may be helpful to you, it's built on angular, and haven't been touched in a while, but last I checked it was pretty nice.
