### ISSUE TITLE
isPlayable should check if the game is unscorable

### ISSUE THREAD

**Issue by rigoparis** [clux/tournament#34]
I noticed that isPlayable doesn't check if the game is unscorable... for instance... I'm at round 3 of a Duel with all games scored and I want to edit a match from Round 1, the isPlayable validation returns true even if editing that match would cause a history rewrite and possibly leave the tournament in an invalid state... and if you think about it, a game is playable only if its scorable.

**Comment by clux** [comment]
Well, `isPlayable` is checked in `unscorable`, [along with other conditions](https://github.com/clux/tournament/blob/116c89d9ec6d39cd383aaf84677e6f5b9d9518bb/lib/tournament.js#L290-L306) (including the subclass override `_verify`) , so it's designed to be a much lighter check. 

The history overwrite thing is only a thing `unscorable` was ever designed to handle.

I will concede that the names for these functions are a bit unintuitive and misleading though.
